### PR TITLE
Zero change to test CI

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
@baronfel This is a no-op change failing, we need a change to CI?

Thanks

**Comment by baronfel** [comment]
This is most likely because the version of 7 previews has floated on the machines and something _else_ is now the problem. So there's probably some actual code changes required.

**Comment by dsyme** [comment]
> This is most likely because the version of 7 previews has floated on the machines and something else is now the problem. So there's probably some actual code changes required.

@baronfel Oh dear, I see, so tricky.....

**Comment by TheAngryByrd** [comment]
Closing as https://github.com/ionide/proj-info/pull/177 should have fixed dotnet 7/f# 7 issues

**Pull request closed without merging**
