### PR TITLE
Simplify getting the build projects from the GraphBuildResult.

### PR DESCRIPTION
**Pull request by nojaf**
I'm currently tinkering with a large solution (300+ projects) and this bit wasn't resolving for me.
@TheAngryByrd I believe this yields the same result, what do you think?

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
This looks a lot more simple! No idea what I was smoking when I wrote this.

**Comment by baronfel** [comment]
Could you try turning them on before we merge this? I'd appreciate the coverage for my own sanity 😂

**Comment by nojaf** [comment]
Yeah, just tried them, they failed on my local main branch.
I did notice something weird where the options of a referenced project are empty, while they are not for non-graph.

**Comment by baronfel** [comment]
Thanks for this! We can look at reenabling graph build tests as a next step.

**Pull request merged**
