### PR TITLE
Revert "set some F#-specific parameters that are used in lieu of setting DOTNET_HOST_PATH"

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Reverts ionide/proj-info#127

### CODE REVIEW

**Comment by baronfel** [comment]
@dsyme we're putting this back in due to the breakages noted [here](https://github.com/ionide/proj-info/pull/127#issuecomment-973002818], but I think that more investigation needs to be done in the FxResolver and related in FCS to determine why you're seeing inconsistent results from what we're seeing here.

**Comment by dsyme** [comment]
> @dsyme we're putting this back in due to the breakages noted here, but I think that more investigation needs to be done in the FxResolver and related in FCS to determine why you're seeing inconsistent results from what we're seeing here.

OK thanks

The problem for FCS is simply that ProjInfo doesn't unset DOTNET_HOST_PATH (after setting it and launching processes).   The presence of the environment variable within the current process screws up FCS logic to use `dotnet` to crack global.json for scripts.

**Comment by baronfel** [comment]
> screws up FCS logic to use dotnet to crack global.json for scripts

referring to [this](https://github.com/dotnet/fsharp/blob/eccf87b7c8ea1a62dbb9481f12c5ba02ca80b8e6/src/fsharp/utils/CompilerLocationUtils.fs#L403-L435) as used [here](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FxResolver.fs#L95-L112)?

**Comment by dsyme** [comment]
Right

**Comment by dsyme** [comment]
It's not a big deal, it just meant I had to do an explicit reset of the env variable here

https://github.com/fsprojects/FSharp.Formatting/blob/2c93118a9e3d2491803988ab32d752b1210c6f31/src/fsdocs-tool/BuildCommand.fs#L851

I think any dotnet tool hosting both proj-ibfo and FCS and processing scripts  will have the problem. It's easy to imagine other such tools over time though :)

**Pull request merged**
