### PR TITLE
Add PackageReferences to nuget packages

### PR DESCRIPTION
**Pull request by Smaug123**
This is an alternative phrasing of https://github.com/ionide/proj-info/pull/215 . Feel free to pick either one depending on which you prefer.

---

I think we are currently simply missing all `PackageReference`s?

There's no corresponding `NuGetPackageId` on a `PackageReference`, so I've gone with simply obtaining the `Include` value.

The whitespace changes earlier in the file are the result of `dotnet fantomas .`.

### CODE REVIEW

**Comment by baronfel** [comment]
Fascinating that what we had didn't capture all of the PackageReferences - maybe we aren't targeting the right design-time target or something?  This seems good to add in any case.

I'd be interested to see if SDK-inserted implicit PackageReferences (e.g. if you publish self contained for another RID) also get shown here.

**Comment by baronfel** [comment]
I'm ok with doing the one-pass check here too - perf is important and doing things in single-pass is an easy way to deal with it.

**Comment by Smaug123** [comment]
If there's a chance of overlap, perhaps we might need to check for duplicates in the result 😨

**Comment by Smaug123** [comment]
There are indeed overlaps, in the case of `PackageReference Update=` I believe:

```
[0] = {Types.PackageReference} { Name = "Nerdbank.GitVersioning"\n  Version = "3.6.143"\n  FullPath =\n   "/Users/patrick/Documents/GitHub/WoofWare.Myriad/WoofWare.Myriad.Plugins/Nerdbank.GitVersioning" }
[1] = {Types.PackageReference} { Name = "FSharp.Core"\n  Version = "6.0.1"\n  FullPath =\n   "/Users/patrick/Documents/GitHub/WoofWare.Myriad/WoofWare.Myriad.Plugins/FSharp.Core" }
[2] = {Types.PackageReference} { Name = "WoofWare.Whippet"\n  Version = "0.1.2"\n  FullPath =\n   "/Users/patrick/Documents/GitHub/WoofWare.Myriad/WoofWare.Myriad.Plugins/WoofWare.Whippet" }
[3] = {Types.PackageReference} { Name = "Fantomas.Core"\n  Version = "6.1.1"\n  FullPath =\n   "/Users/patrick/.nuget/packages/fantomas.core/6.1.1/lib/netstandard2.0/Fantomas.Core.dll" }
[4] = {Types.PackageReference} { Name = "Fantomas.FCS"\n  Version = "6.1.1"\n  FullPath =\n   "/Users/patrick/.nuget/packages/fantomas.fcs/6.1.1/lib/netstandard2.0/Fantomas.FCS.dll" }
[5] = {Types.PackageReference} { Name = "FSharp.Core"\n  Version = "6.0.1"\n  FullPath =\n   "/Users/patrick/.nuget/packages/fsharp.core/6.0.1/lib/netstandard2.1/FSharp.Core.dll" }
[6] = {Types.PackageReference} { Name = "System.Diagnostics.DiagnosticSource"\n  Version = "7.0.0"\n  FullPath =\n   "/Users/patrick/.nuget/packages/system.diagnostics.diagnosticsource/7.0.0/lib/net6.0/System.Diagnostics.DiagnosticSource.dll" }
```

**Comment by Smaug123** [comment]
I'm afraid I think my desired outcome ("get the path to the DLLs implied by all NuGet packages tagged with my particular custom metadata item") is beyond my current powers. The `ReferencePath`s appear to be the complete listing of all DLL imports, but I don't have a good way of filtering out e.g. the .NET runtime itself from those references.

**Comment by baronfel** [comment]
@Smaug123 how are you approaching this? Do you have a binlog that you're looking at? If so, it might be useful to look at the `ResolvePackageAssets` Target/Task and see if the outputs of that give you what you need. If so, we can make sure that target is in our list of design time targets so that you can grab and filter Items from that.

**Comment by Smaug123** [comment]
(I've used up basically all my extracurricular energy for a while; I may eventually come back to this, but very possibly not. I solved my immediate problem using msbuild XML instead.)

**Pull request closed without merging**
