### PR TITLE
add in support for more dotnet environment variables

### PR DESCRIPTION
**Pull request by baronfel**
Should address #116 for probing and help prevent the loops called out there.

### CODE REVIEW

**Comment by baronfel** [comment]
@Booksbaum how does this look to you?

**Comment by baronfel** [comment]
yeah, that one has been flaky for a while, I'm not entirely sure what's going on there :(

**Comment by baronfel** [comment]
I went ahead and did the sdk/runtime parsing from the command line, which results in a slight api surface area change but its a good change IMO.

**Comment by Booksbaum** [comment]
Works great 👍

(and...uhh.....reason why the previous version didn't work for me: I forgot to checkout the correct branch....)

-------------------

A note about `DOTNET_ROOT`: it's only set when run via `dotnet run ...`, NOT when running the compiled exe directly (which makes sense: compiled/published program should be self-sufficient) (and doesn't matter when falling back to `dotnet` from `Path`).  
But I think that's fine for a dev tool/lib like this here.

**Comment by baronfel** [comment]
testing this locally on the update-proj-info branch of FSAC and still not able to get `dotnet test` working locally on my Windows machine, so I'm note quite ready to merge this in case there's something else that's missing.

**Comment by Booksbaum** [comment]
But that's a different issue. fsharp/FsAutoComplete#837 is just the `--version` child spawn (on all OS) when there's no `DOTNET_HOST_PATH`. That's the case with `dotnet run` or just starting the exe. But with `dotnet test` that was already set  
-> no change when running `dotnet test` because it already pointed to the correct dotnet executable 


But the general issue with some (a lot...) failing test on windows still remains. And no real idea why. It hangs somewhere when loading projects (that's why I used `dotnet run` -> unlike `dotnet test` this has logging enabled (and is easier customizable via main)).  
But that's a different issue, not related to this here.

**Comment by baronfel** [comment]
That's a fair point, I am conflating a few things.

**Pull request merged**
